### PR TITLE
Update README.md to have information about ES6

### PR DESCRIPTION
**Pull request by ev1stensberg**
Added a small paragraph about why we use ES6 like this so we don't seem like matrix minions when they review our code.

### CODE REVIEW

**Comment by knowbody** [comment]
Thank you for your PR we appreciate your time spent on it, but I don't think this is relevant, we can just make a comment when we are reviewing the PR. It's not like we get PRs with new examples often. Also I don't like the language used there.

Closing, please reopen if this is needed.

**Comment by ev1stensberg** [comment]
Figured out this would be the best solution. Do we want to make comments on all of the code that uses component? Think it would be great if we could give users a indication of why we use component for them to fully understand. They are usually first time users. What do you suggest? Also, sorry for the language used it was suppose to be ironic :smile:

**Comment by knowbody** [comment]
I think this is just a matter of preference. I don't think it matters if someone uses `React.Component` or just `Component`, I prefer the latter but again it's just a matter of preference. If we would want to enforce something like this (which I don't think makes sense) we would do so in our eslint rules.

**Comment by ev1stensberg** [comment]
I agree. So we would not give them any indication of why we use Component instead in the examples? I'll be happy to make a new PR with a single line comment in all of the examples that uses ES6 components, though ✋🏽

**Comment by knowbody** [comment]
does it matter?

**Comment by ev1stensberg** [comment]
Stated it in #3253 . Think it would be a nice addition, but that is really up to you guys.

**Comment by knowbody** [comment]
I don't think it's needed. Feel free to reopen if you think otherwise.

**Comment by ev1stensberg** [comment]
Then it's settled ✌🏾️ Sorry for wasting your time with this PR!

**Comment by knowbody** [comment]
it's cool, I don't mind.

**Comment by knowbody** [comment]
pressed wrong button lol

**Comment by taion** [comment]
Yeah, this is fine I think – it wouldn't make sense to explain all of our ES6 usage. This is consistent with what's used in e.g. react-future's module examples, and in react-redux, so I think this is fine.

**Pull request closed without merging**
