### PR TITLE
Update API.md

### PR DESCRIPTION
**Pull request by peterbsmith2**
I think this should be added into the docs because it is available today on the master branch, despite Dan Abramov adding the language in #3444 on the `next` branch

### CODE REVIEW

**Comment by timdorr** [comment]
Nope, this [isn't currently in master](https://github.com/reactjs/react-router/blob/master/modules/withRouter.js). It'll be on the next major.

**Comment by peterbsmith2** [comment]
How confusing, @gaearon posted [this video](https://egghead.io/lessons/javascript-redux-using-withrouter-to-inject-the-params-into-connected-components) making use of it. I  really thought I was doing something wrong to not be able to use it. Its not great to have a video out using an un-released feature.

**Comment by timdorr** [comment]
He's using the 3.0.0-pre version in the video series, so it's not outdated
once 3.0 goes final.

On Mon, Jun 6, 2016, 9:36 PM Peter B Smith <notifications@github.com> wrote:

> How confusing, @gaearon <https://github.com/gaearon> posted this video
> <https://egghead.io/lessons/javascript-redux-using-withrouter-to-inject-the-params-into-connected-components>
> making use of it. I really thought I was doing something wrong to not be
> able to use it. Its not great to have a video out using an un-released
> feature.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/reactjs/react-router/pull/3519#issuecomment-224138021>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABF2k1PVgawRWv6sj7BP8nL8AZJTOsVks5qJMsPgaJpZM4IvTXd>
> .
>
-- 

-Tim

**Comment by peterbsmith2** [comment]
@timdorr thanks for following up. I am trying to now make-use-of the feature in my own local project to follow along with the video. My thought is to clone down the repo and checkout the `next` branch and use that. If that sounds nonsensical, I'm interested to know what the best thing to do is.

**Comment by taion** [comment]
`npm i react-router@next`

**Pull request closed without merging**
