### PR TITLE
Improve syntax highlighting in docs

### PR DESCRIPTION
**Pull request by DannyDelott**
Before:
screen shot 2016-09-06 at 5 53 21 pm

After:
screen shot 2016-09-06 at 5 53 37 pm

### CODE REVIEW

**Comment by taion** [comment]
Let's bulk replace every instance of "jsx" with just "js" for syntax highlighting.

**Comment by DannyDelott** [comment]
It does give nice attribute highlighting when the line is strictly JSX:

with `jsx`:

screen shot 2016-09-06 at 5 59 10 pm

with `javascript`:

screen shot 2016-09-06 at 5 59 33 pm

**Comment by taion** [comment]
Yes, but it's better to be consistent, and in fact it's broken right now for everything that uses `import`.

**Comment by taion** [comment]
Do it for everything. Just do a bulk `git grep` replace of "\`\`\`jsx" with "\`\`\`js".

**Comment by DannyDelott** [comment]
Done and squashed!

**Comment by taion** [comment]
Eh, you really like "\`\`\`javascript" over "\`\`\`js"? 😛

**Comment by DannyDelott** [comment]
Didn't know there was just a `js`, one sec...

**Comment by taion** [comment]
Save the bytes on a shallow clone and all. We use it in the README: https://raw.githubusercontent.com/reactjs/react-router/master/README.md

**Comment by DannyDelott** [comment]
`js` it is!

**Comment by taion** [comment]
Thanks!

**Pull request merged**
