### PR TITLE
Define presentational components as stateless functional components

### PR DESCRIPTION
**Pull request by dylancompanjen**
For stateless components (also called presentational/dumb components), Facebook introduced a much simpler syntax than ES6 classes.
Stateless functional components simply take props as an argument and return the element you want to render.

### CODE REVIEW

**Comment by timdorr** [comment]
Hmm, I don't think there's any reason not to use these. @ryanflorence @taion Do you guys remember any reason for not going with functional components? Or was it just a timing thing prior to React 0.14?

**Comment by taion** [comment]
This is just in the examples? Cool! Not sure why we used ES6 components there given that our style guide explicitly calls for `React.createClass` elsewhere in code.

One nit – could we be consistent between using `props` as an argument v spreading out the individual props in the function definition?

**Comment by dylancompanjen** [comment]
Consistency added. Personally I only noticed it in the examples as I needed the transition example today.

**Comment by timdorr** [comment]
Thanks!

**Pull request merged**
