### PR TITLE
[DO NOT MERGE] Deprecate routes with nested absolute paths

### PR DESCRIPTION
**Pull request by taion**
Ref #3172

### CODE REVIEW

**Comment by mjackson** [comment]
👍  Thanks, @taion.

**Comment by mjackson** [comment]
Please don't merge until we know what release this will be a part of.

**Comment by taion** [comment]
I'd recommend against merging this for a while, BTW. I had it merged on rrtr for like a few hours, but changed my mind and backed it out: https://github.com/taion/rrtr/pull/11. This doesn't add any direct value to users until a breaking release that actually gets rid of the underlying feature is possible.

**Comment by ryanflorence** [comment]
Added the 3.0 milestone. We don't want to release this until we have features/improvements that depend on it, otherwise it's just annoying to our users. If we get those going we can move this to an earlier release.

**Comment by taion** [comment]
I'm sorry, I somehow literally lost the branch or repo or something that I submitted this PR from. I'm going to need to remake it.

**Comment by ryanflorence** [comment]
Maybe it's in the rrtr fork? :trollface:

**Comment by taion** [comment]
Replaced by https://github.com/reactjs/react-router/pull/3319.

**Pull request closed without merging**
