### PR TITLE
Fix remaining issues with #3556

### PR DESCRIPTION
**Pull request by taion**
cc @avanderhoorn: This is what I meant

### CODE REVIEW

**Comment by taion** [comment]
Specifically:

1) Make similar APIs consistent
2) Pick abstractions that maximize code reuse
3) Leverage existing test cases when possible

**Comment by timdorr** [comment]
LGTM.

**Comment by taion** [comment]
@timdorr wdyt of cutting 2.5.0 from this?

**Comment by timdorr** [comment]
I say go for it. 👍

**Comment by taion** [comment]
Okay – I'll hold off on releasing another v3 alpha though.

**Pull request merged**
