### PR TITLE
Add docs for the Link prop `onlyActiveOnIndex`

### PR DESCRIPTION
**Pull request by chrisbolin**

### CODE REVIEW

**Comment by taion** [comment]
This is sort of considered an implementation detail here. Why would you not be able to use `<IndexLink>`?

**Comment by chrisbolin** [comment]
I think the tutorial gives a [pretty good case for this](https://github.com/reactjs/react-router-tutorial/blob/start/lessons/09-index-links.md#onlyactiveonindex-property).

**Comment by chrisbolin** [comment]
Basically it's helpful when building abstractions of `<Link>`

**Comment by taion** [comment]
Thanks.

**Comment by chrisbolin** [comment]
✋

**Pull request merged**
