### PR TITLE
Minor change to CSS + Change from false to !true

### PR DESCRIPTION
**Pull request by ev1stensberg**
Added page to align centre with list margins.

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Edit: Fixed margins to have all examples at 100vh

**Comment by ev1stensberg** [comment]
Edit: Ran !true vs false in JsPerf and found out it was more performance friendly to use !true instead of false. [JsPerfLink](http://jsperf.com/nottrue-vs-false) Now, I do not know how this is on large scale. It's a rather bold move to use !true in my eyes, so if you want to merge only the css and not the opt, that is fine for me.

**Comment by timdorr** [comment]
This is really splitting hairs. Thanks for the PR, but this just makes it needlessly complex to read.

**Comment by ev1stensberg** [comment]
Sure! What did you think about the CSS alone?

**Pull request closed without merging**
