### PR TITLE
Docs: add list of exported PropTypes

### PR DESCRIPTION
**Pull request by lPadier**
Add list of exported PropTypes.
Specified the behavior of the falsy PropType

### CODE REVIEW

**Comment by taion** [comment]
Why is this even part of our public API? Does anybody use this?

**Comment by lPadier** [comment]
I use the location PropType validator in views where I need access to the query parameters,

**Comment by taion** [comment]
`query` isn't even part of the specified shape on `location` though: https://github.com/reactjs/react-router/blob/v2.0.1/modules/PropTypes.js#L17-L23

**Comment by lPadier** [comment]
Per https://github.com/mjackson/history/blob/v2.0.1/docs/QuerySupport.md
query is only a part of the location object if the user has enabled QuerySupport in their history object, which browserHistory has:
https://github.com/reactjs/react-router/blob/v2.0.1/modules/useRouterHistory.js#L6.

**Comment by taion** [comment]
What I'm saying, though, is that the `location` prop type gives you no assurances as to the presence of a query.

**Comment by taion** [comment]
Well, I shouldn't bikeshed this. This is a strict improvement for now, though we should consider no longer exporting `PropTypes`.

**Pull request merged**
