### PR TITLE
Fix references to PropTypes.router

### PR DESCRIPTION
**Pull request by troyastorino**
`Router.PropTypes.router` is `undefined`. The tutorial uses `React.PropTypes.object`, and which seems to work properly

### CODE REVIEW

**Comment by taion** [comment]
See discussion in https://github.com/reactjs/react-router/issues/3310.

I'm really thinking we should be exporting this as `routerShape` or something. Doing e.g.

```js
import Router from 'react-router'
```

is weird, and is a name conflict with the actual `<Router>`.

**Comment by taion** [comment]
cc @xabikos

**Comment by timdorr** [comment]
> Doing e.g.
```js
import Router from 'react-router'
```
is weird, and is a name conflict with the actual `<Router>`.

Which is why you would normally do 
```js
import { PropTypes } from 'react-router';
// or better yet...
import { PropTypes as routerPropTypes } from 'react-router';
```
We can better fix this by including that import statement in the upgrade doc.

**Comment by taion** [comment]
What do you think about exporting that as `routerShape`, the way react-intl exports `intlShape` for its context object?

**Comment by troyastorino** [comment]
Makes sense! From a newcomer's perspective, seeing 

```js
  contextTypes: {
    router: routerPropTypes.router
  }
```

would be very clear. Seeing `PropTypes` instead of `routerPropTypes` would prompt confusion with `PropTypes` exposed from React

**Comment by taion** [comment]
I'm still in favor of revamping propTypes entirely. Most of these: https://github.com/reactjs/react-router/blob/master/modules/PropTypes.js#L27-L30 are not useful externally. We just need `routerShape`.

**Pull request closed without merging**
