### PR TITLE
Don't crash on invalid uri query parameters.

### PR DESCRIPTION
**Pull request by bae-unidev**
Replace decodeURIComponent with _tryDecodeURIComponent to ignore crash "URIError: malformed URI sequence".

### CODE REVIEW

**Comment by taion** [comment]
The router offers an `onError` callback to handle errors, though. Why not just use that? `null` doesn't seem like a suitable fallback here.

**Comment by bae-unidev** [comment]
I don't know that not call `onError` handler when decodeURIComponent throwing.
Is `History` of the problem?

**Comment by taion** [comment]
`onError` on the router catches all errors

**Comment by bae-unidev** [comment]
```
<Router history={ hashHistory } onError={ (e) => console.error(e) }>
   <Route path="/" component={ Index } />
</Router>
```
path: /#/**%**
My browser(Chrome 50.0.2661.94) throw `Uncaught URIError: URI malformed.` 
did you mean it?

**Comment by taion** [comment]
I see – we should catch the error there from `matchRoutes`, then. The correct behavior here is still to hit the error handling logic.

**Comment by bae-unidev** [comment]
What if add `callback(error, matched)` parameter to `matchPattern` function in PatternUtils.js?

**Comment by taion** [comment]
It doesn't need that – it's synchronous.

**Comment by bae-unidev** [comment]
So, you mean I should handle error in `matchPattern` function, not by using callback?
If so, when user pass malformed URI, router will not working. Is it right?

**Comment by taion** [comment]
I am saying to just add a `try`/`catch` here: https://github.com/reactjs/react-router/blob/master/modules/matchRoutes.js#L91 and invoke `callback` with the error if there was one.

**Comment by bae-unidev** [comment]
I modified it that you saying. Is it fine?

**Comment by taion** [comment]
Thanks! LGTM.

**Pull request merged**
