### PR TITLE
Move ES module build to es/

### PR DESCRIPTION
**Pull request by taion**
This makes us consistent with Redux

### CODE REVIEW

**Comment by timdorr** [comment]
Let's make a note of this in the Changelog so that those living on the edge and building via these files know to update.

**Comment by ryanflorence** [comment]
isn't moving the directory of something a breaking change?

**Comment by ryanflorence** [comment]
oh, nvm, `main` solves it.

**Comment by taion** [comment]
`jsnext:main`, but yeah – the idea is that users should be importing this as `'react-router'` anyway, not reaching into `es/` manually.

**Pull request merged**
