### PR TITLE
Easy Doc navigation

### PR DESCRIPTION
**Pull request by ev1stensberg**
Made it easier to navigate between documents.

### CODE REVIEW

**Comment by Kallikrein** [comment]
Just reading the commits, I wonder : shouldn't the link have relative url ? I noticed some absolute links to your fork.

example : 'https://github.com/ev1stensberg/react-router/blob/master/docs/guides/ConfirmingNavigation.md'

**Comment by ev1stensberg** [comment]
@Kallikrein thanks, been copy + pasting from my own repo, lol. I'll fix it in a jiffy!

**Comment by Kallikrein** [comment]
You still use absolute url, I patched a file in an example commit for you.

 -```[Next Section - Histories](https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md)```
+```[Next Section - Histories](/docs/guides/Histories.md)```

**Comment by ev1stensberg** [comment]
Think that's a matter of preference, there's no big perf in leaving routes absolute. As well as some of the links are outside the current folder. I'll leave that for he review(if so)

**Comment by timdorr** [comment]
These docs aren't in any particular order, so having "next" links doesn't really apply. I'd look into helping on @knowbody's docs repo, so we can keep that ball rolling and eventually get that moved back here.

**Comment by ev1stensberg** [comment]
FWIW- made each link redirected ( Next - Section ) according to the content overview.

**Pull request closed without merging**
