### PR TITLE
Move the ES modules build where it belongs

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
(not the trash can... rimshot denied)

**Comment by timdorr** [comment]
Didn't this cause problems last time? I forget the details...

**Comment by taion** [comment]
People complained that the move was semver-breaking (they were importing directly from `react-router/es6` instead of pointing webpack at `jsnext:main`). Well, this is a major version bump, so now that's no longer a blocker.

**Comment by timdorr** [comment]
Ah, forgot to check this was on `next`. All good!

**Pull request merged**
