### PR TITLE
[HOLD OFF ON MERGING] Deprecate routeParams

### LINKED ISSUE #3549: Empty routeParams cause
I have several routes.
They have their shouldComponentUpdate functions called, and the only thing that invalidates them is empty object routeParams (current and previous values are {}).

Am I doing something wrong?
Is there a way not to inject these?

If this is intended, wouldn't it be a good idea to always return the same empty object in getRouteParams.js (maybe overthinking it, if there is another way to solve)

### PR DESCRIPTION
**Pull request by taion**
Closes #3549

### CODE REVIEW

**Comment by taion** [comment]
Don't merge this until after we cut v2.5.2 with #3591.

This is ahead of dropping `routeParams` entirely in v3.

**Comment by timdorr** [comment]
👍

**Comment by taion** [comment]
Hold off on merging this for a bit. Want to think about it a little.

**Comment by taion** [comment]
Again closing this for now since I don't think it should be merged as-is. Better to generate "real" `routeParams` per route, maybe, and expose those.

**Pull request closed without merging**
