### PR TITLE
Pass params and location as props in withRouter()

### LINKED ISSUE #3439: Make withRouter() update in response to context changes
I wonder if you’d be up for accepting a PR like #3430 but for `withRouter()` (#3352). This would eliminate the problem of “how do I connect to the router state in Redux in a deep component” because people would just wrap their deep components with `withRouter` and be guaranteed to get the right `params`.

If this makes sense to you, I’d submit a PR that moves the context fix to be used by `withRouter`, and change `Link` to use `withRouter` internally.

### PR DESCRIPTION
**Pull request by gaearon**
Fixes #3439 for good as discussed in https://github.com/reactjs/react-router/pull/3443#issuecomment-217972967.

### CODE REVIEW

**Comment by export-mike** [comment]
out of interest is there a reason why this isn't in v2.x.x? I'm having a go at upgrading to 3.0.0-alpha-1

**Comment by export-mike** [comment]
I've updated to 3.0.0-alpha-1 I'm fortunate my codebase just works with v3.0!

**Comment by pranav-xx** [comment]
I upgraded to 3.0.0-alpha-1 so that I can use withRouter. However I get 
Uncaught TypeError: Cannot read property 'getCurrentLocation' of undefined
@ following line:
`!history.getCurrentLocation ? process.env.NODE_ENV !== 'production' ? (0, _invariant2.default)(false, 'You have provided a history object created with history v2.x or ' + 'earlier. This version of React Router is only compatible with v3 ' + 'history objects. Please upgrade to history v3.x.') : (0, _invariant2.default)(false) : void 0;`

Please suggest

**Comment by pranav-xx** [comment]
Ok, so looks like I hurried to put this comment instead of searching. I solved this using history

as explained by "gajus" here: https://github.com/reactjs/react-router/issues/2866

**Pull request merged**
