### PR TITLE
Do not include deprecation code in production builds

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
This just moves the function declaration into the `__DEV__` guard; otherwise it ends up in production builds.

**Comment by timdorr** [comment]
Saves me the `curl https://github.com/taion/rrtr/pull/18.patch | git am` :P

:+1:

**Comment by taion** [comment]
Was that what you did? You can actually add that repo as an upstream to your local repo, and `git cherry-pick` from there.

**Comment by timdorr** [comment]
Given the potential for divergence, I've found it's better to essentially cherry pick that way, rather than build up a "frankenrepo" and a huge `.git` folder.

**Pull request merged**
