### PR TITLE
Support React v15 on legacy v0.13 branch

### PR DESCRIPTION
**Pull request by taion**
I was going through cleaning up old branches, and realized I still had this one sitting around.

Might as well check it in? I think it works.

From https://github.com/reactjs/react-router/issues/3281, but looks like nobody's desperately in need of a release or anything.

### CODE REVIEW

**Comment by taion** [comment]
I want to delete this branch but I don't want the code to go away forever 😛 

e.g. even if I close this PR, I can use the PR to restore the branch! 😄

**Comment by ljharb** [comment]
This would be great to get a release of!

**Comment by taion** [comment]
@ljharb Can you let me know if this code actually works though? I have no way of checking.

**Comment by ljharb** [comment]
I can only confirm it works secondhand atm, but by tomorrow I'll have first-hand confirmation :-)

**Comment by taion** [comment]
Let me know. We said in #3281 that we were willing to release this, so might as well resolve this. (I really don't like having stale branches sitting around).

@timdorr You okay with making this change?

**Comment by taion** [comment]
@ljharb ping

**Comment by ljharb** [comment]
@taion sorry; i've been traveling. I believe @goatslacker has verified that this works beautifully, but hopefully he can chime in :-)

**Comment by goatslacker** [comment]
@taion been traveling as well, yeah the change works well.

**Comment by taion** [comment]
Any objections to releasing this?

**Comment by goatslacker** [comment]
No, go for it.

**Comment by taion** [comment]
That was meant for @timdorr 😄

**Comment by timdorr** [comment]
Sorry, having to swap out some production systems on the fly at work, so I've been running around like a chicken with my head cut off all day. Haven't even eaten lunch :(

LGTM. Worst case you can yank the version if it's bad.

**Comment by taion** [comment]
Sorry! Just wanted to make sure your "but why?" was addressed. (:

**Comment by timdorr** [comment]
It was more of a joking "why reach into the past" kind of thing. No worries :)

**Comment by lencioni** [comment]
Thanks for your work on this!

**Comment by pixeldrew** [comment]
I can confirm that 13.4 worked without these changes on 15.4. This seems to be mostly fixes to the unit tests. There is one fix that needs to be addressed in the Link component that wasn't addressed, that is a warning for applying additional props onto the a tag in the render func.

**Comment by taion** [comment]
Ugh okay this is released as v0.13.6. I vote that we should just delete the `0.13.x` and say it's officially dead going forward, explicitly with no PRs or further releases.

**Comment by timdorr** [comment]
Agreed. I'll go nuke it into oblivion now.

**Comment by ljharb** [comment]
Deleting published code is not so good :-( please don't do that, even if there won't be further releases.

**Comment by taion** [comment]
Well, the former tip of the 0.13.x branch and the v0.13.6 tag are the same. I don't think we should delete the tag. No code is gone.

**Comment by timdorr** [comment]
It's not deleted. Only the branch is gone. The tag remains: https://github.com/reactjs/react-router/tree/v0.13.6

**Comment by pixeldrew** [comment]
I believe they are talking about just deleting the branch not the tag.
Deleting the branch should be fine. A warning should be placed in the
Readme that 0.13 is not supported anymore and if someone wishes to support
 the release they can branch from the tag.

> --
Drew Foehn
drew@foe.hn
+1 (347) 443 4031

**Comment by ljharb** [comment]
Just making sure, thanks :-)

**Pull request merged**
